// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXbPgqqwrFHSkA9RYYm9iCFEPRq1tV7aM',
    appId: '1:956518361767:web:351cd97a718fc5f1880982',
    messagingSenderId: '956518361767',
    projectId: 'brisa-supply-chain',
    authDomain: 'brisa-supply-chain.firebaseapp.com',
    storageBucket: 'brisa-supply-chain.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY5BCpjobQ6NM2oovgdO8zyqVqUHkRmG8',
    appId: '1:956518361767:android:6031860e86d859f9880982',
    messagingSenderId: '956518361767',
    projectId: 'brisa-supply-chain',
    storageBucket: 'brisa-supply-chain.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqXFeZl4YQhJDscvUq15B9o7_7rydRFSk',
    appId: '1:956518361767:ios:8dd7b5ecb2ba67ce880982',
    messagingSenderId: '956518361767',
    projectId: 'brisa-supply-chain',
    storageBucket: 'brisa-supply-chain.firebasestorage.app',
    androidClientId: '956518361767-bhn1i9uuivhpmkruhdftvv1hiucff39q.apps.googleusercontent.com',
    iosClientId: '956518361767-oeg7o3nuhtfp4kmhlqlor1bn4jhck23u.apps.googleusercontent.com',
    iosBundleId: 'com.example.brisaSupplyChain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqXFeZl4YQhJDscvUq15B9o7_7rydRFSk',
    appId: '1:956518361767:ios:8dd7b5ecb2ba67ce880982',
    messagingSenderId: '956518361767',
    projectId: 'brisa-supply-chain',
    storageBucket: 'brisa-supply-chain.firebasestorage.app',
    androidClientId: '956518361767-bhn1i9uuivhpmkruhdftvv1hiucff39q.apps.googleusercontent.com',
    iosClientId: '956518361767-oeg7o3nuhtfp4kmhlqlor1bn4jhck23u.apps.googleusercontent.com',
    iosBundleId: 'com.example.brisaSupplyChain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXbPgqqwrFHSkA9RYYm9iCFEPRq1tV7aM',
    appId: '1:956518361767:web:ea1ffadda3efa87e880982',
    messagingSenderId: '956518361767',
    projectId: 'brisa-supply-chain',
    authDomain: 'brisa-supply-chain.firebaseapp.com',
    storageBucket: 'brisa-supply-chain.firebasestorage.app',
  );
}
